package UI;

import Controllers.EmployeeLoginController;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class EmployeeSignInBox implements ActionListener{
    Label userNameLabel;
    TextField userNameText;
    Label passwordLabel;
    PasswordField passwordText;
    Button signIn;
    MyJFrame frame;
    Panel panel;
    EmployeeLoginController employeeLoginController;

    public EmployeeSignInBox(EmployeeLoginController employeeLoginController){

        this.employeeLoginController = employeeLoginController;

        frame = new MyJFrame();
        frame.createFrame("Employee Login", 300, 300);

        panel = new Panel();
        panel.createPanel(20, 30, 20, 30, "null", 0, 1, 10, 10, frame.getJFrame());

        userNameLabel = new Label();
        userNameLabel.createLabel(50, 8, 80, 20, frame.getJFrame(), "EmployeeID");
        userNameText = new TextField();
        userNameText.createTextField(frame.getJFrame(), 50, 27, 193, 28);

        passwordLabel = new Label();
        passwordLabel.createLabel(50, 55, 70, 20, frame.getJFrame(), "Password");
        passwordText = new PasswordField();
        passwordText.createPasswordField(frame.getJFrame(), 50, 75, 193, 28);

        // create button for signIn
        signIn = new Button();
        signIn.createButtonWithIcon(frame.getJFrame(), "SignIn", 90, 110, 100, 50);
        signIn.getButton().addActionListener(this);
    }

    /**
     * This method is called when the "SignIn" button is clicked.
     * @param evt The ActionEvent object generated by the "SignIn" button click.
     */    @Override
    public void actionPerformed(ActionEvent evt) {
        int employeeID = Integer.parseInt(this.userNameText.getTextField().getText());
        String password = new String(passwordText.getPasswordFieldField().getPassword());
        try{
            // Call the controller to check employee login
            employeeLoginController.checkLogin(employeeID, password);
//            JOptionPane.showMessageDialog(null, "Login Successful!");
            new EmployeePortalBox().createEmployeePortalBox();
            frame.getJFrame().dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
